# Generated by Django 2.2.7 on 2019-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Specialty', models.CharField(max_length=50, verbose_name='Спеціальність')),
                ('student_Group', models.CharField(max_length=50, verbose_name='Група')),
                ('student_Number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('student_Name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('student_Enterprise', models.CharField(max_length=80, verbose_name='Підприємство (<назва українською>, м. <місто>)')),
                ('student_Contract', models.CharField(blank=True, max_length=50, null=True, verbose_name='Договір')),
                ('student_Points', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Бали')),
                ('student_Rating', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оцінка')),
                ('student_The_theme_of_work', models.TextField(max_length=250, verbose_name='Тема роботи')),
                ('student_The_topic_of_work_in_English', models.TextField(max_length=250, verbose_name='Тема роботи англійською мовою')),
                ('student_Last_name_First_name_in_English', models.CharField(max_length=100, verbose_name="Прізвище Ім'я англійською")),
                ('student_Manager', models.CharField(max_length=50, verbose_name='Керівник')),
                ('student_Email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
