# Generated by Django 2.2.7 on 2019-11-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Enterprise',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підприємство (<назва українською>, м. <місто>)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Last_name_First_name_in_English',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Прізвище Ім'я англійською"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Manager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Керівник'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Specialty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_The_theme_of_work',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Тема роботи'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_The_topic_of_work_in_English',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Тема роботи англійською мовою'),
        ),
    ]
