# Generated by Django 2.2.7 on 2019-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_group_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_Title', models.CharField(max_length=150, verbose_name='Назва')),
                ('enterprise_City', models.CharField(max_length=50, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Підприємство',
                'verbose_name_plural': 'Підприємства',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_Surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('teacher_First_name', models.CharField(max_length=50, verbose_name='Імя')),
                ('teacher_Middle_name', models.CharField(max_length=50, verbose_name='По батькові')),
                ('teacher_scientific_Degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наукова ступінь')),
                ('teacher_Email', models.CharField(blank=True, max_length=80, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
